-- ICT Service Request Management System
-- Run this in Supabase > SQL Editor.

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  requester_name text not null,
  department text not null,
  category text not null,
  description text not null,
  priority text not null check (priority in ('Low', 'Medium', 'High')),
  status text not null default 'Pending'
    check (status in ('Pending', 'In Progress', 'Completed')),
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade
);

alter table public.service_requests enable row level security;

-- Remove old exercise policies first so this script can be safely re-run.
drop policy if exists "Authenticated users can view requests" on public.service_requests;
drop policy if exists "Authenticated users can insert requests" on public.service_requests;
drop policy if exists "Authenticated users can update requests" on public.service_requests;
drop policy if exists "Authenticated users can delete requests" on public.service_requests;

create policy "Authenticated users can view requests"
on public.service_requests
for select
to authenticated
using (true);

create policy "Authenticated users can insert requests"
on public.service_requests
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Authenticated users can update own requests"
on public.service_requests
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Authenticated users can delete own requests"
on public.service_requests
for delete
to authenticated
using (auth.uid() = user_id);

-- Optional: useful indexes for search/filter performance.
create index if not exists idx_service_requests_status
on public.service_requests(status);

create index if not exists idx_service_requests_priority
on public.service_requests(priority);

create index if not exists idx_service_requests_user_id
on public.service_requests(user_id);

-- Optional sample records:
-- Replace the UUID with the ID of a real Supabase Auth user.
-- insert into public.service_requests
-- (requester_name, department, category, description, priority, user_id)
-- values
-- ('Juan Dela Cruz', 'Registrar', 'Network Problem',
--  'Computer cannot connect to university Wi-Fi.', 'High',
--  'YOUR-AUTH-USER-UUID');
